<div class="ws-bloc-policy">
  <div class="grid-x align-center">
    <div class="cell large-9 medium-12 small-12">
      <div class="ws-policy-body">
        <div class="grid-x grid-padding-x align-middle">
          <div class="cell small-12 medium-6 large-6">
            <div class="ws-policy-label">
              <span runat="server" id="lblConsentPolicyText"></span>
            </div>                        
          </div>
          <div class="cell auto">
            <div class="grid-x align-center medium-align-left">
              <div class="stacked-for-small button-group">
                <a runat="server" id="cmdConsentPolicyValid" class="ws-policy-cmd valid">Je valide</a>
                <a href="https://cookiesandyou.com/" target="_blank" class="ws-policy-cmd info">Plus d'informations</a>                
              </div>
            </div>
          </div>          
        </div>
      </div>
    </div>            
  </div>
 </div>
