<div class="ws-bloc-footer">
  <div class="grid-x grid-padding-x">
    <div class="cell small-6 text-left">
      <dnn:copyright ID="dnnCopyright" runat="server" />
    </div>
    <div class="cell small-6 text-right">
      <div class="grid-x"></div>
      <dnn:terms id="dnnTerms" runat="server" />&nbsp;|
      <dnn:privacy id="dnnPrivacy" runat="server" />
    </div>
  </div>
</div>
<div runat="server" id="divConsentPolicy"></div>

